version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              build-essential \
              zlib1g-dev \
              uuid-dev \
              libdigest-sha-perl \
              libelf-dev \
              bc \
              bzip2 \
              bison \
              flex \
              git \
              gnupg \
              iasl \
              m4 \
              nasm \
              patch \
              python \
              wget \
              gnat \
              cpio \
              ccache \

      - run:
          name: Checkout
          command: |
            git clone https://github.com/osresearch/heads
      - run:
          name: qemu-coreboot
          command: |
            make BOARD=qemu-coreboot
      - run:
          name: qemu-linuxboot
          command: |
            make BOARD=qemu-linuxboot
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
