version: 2
jobs:
  build:
    docker:
      - image: _/ubuntu:18.04
    steps:
      - checkout
      - run: 'git clone https://github.com/osresearch/heads'
      - run: 'make BOARD=qemu-coreboot'
      - run: 'make BOARD=qemu-linuxboot'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
